//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CssCsCloud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CssCsCloud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Storage Sync.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdxv9bvu37pjd5r.
        /// </summary>
        internal static string DropboxApiKey {
            get {
                return ResourceManager.GetString("DropboxApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsfy8way52uuf1j.
        /// </summary>
        internal static string DropboxApiSecret {
            get {
                return ResourceManager.GetString("DropboxApiSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyCZUicaxZb7DENX-NMpuDc59S0udi3G9WU.
        /// </summary>
        internal static string GoogleDriveApiKey {
            get {
                return ResourceManager.GetString("GoogleDriveApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 962171380504-jia11p348837sd22iji10nbul76vc7em.apps.googleusercontent.com.
        /// </summary>
        internal static string GoogleOauth2_ClientID {
            get {
                return ResourceManager.GetString("GoogleOauth2_ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZXqAy1VXh2mc-YOxx3fU4QsP.
        /// </summary>
        internal static string GoogleOauth2_Clientsecret {
            get {
                return ResourceManager.GetString("GoogleOauth2_Clientsecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K1t33QJC.
        /// </summary>
        internal static string MegaApiAppKey {
            get {
                return ResourceManager.GetString("MegaApiAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c8eb5627-8b82-43d3-9617-6b8c91d09de9.
        /// </summary>
        internal static string OneDriveClientId {
            get {
                return ResourceManager.GetString("OneDriveClientId", resourceCulture);
            }
        }
    }
}
